name: toronto-shared-bike

include:
  - ../jenkins/docker-compose.yaml
  - ../monitor/docker-compose.yaml

networks:
  ingress_net:
    driver: bridge
  app_net:
    driver: bridge
    internal: true

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx config
      - ./static/robots.txt:/usr/share/nginx/html/robots.txt:ro # Web crawl
    networks:
      - ingress_net
      - app_net
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - jenkins
      - grafana
