services:
  master:
    container_name: master
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    ports:
      - "8089:8089"
    command: >
      -f /mnt/locust/locustfile.py
      --master
      --web-host 0.0.0.0
      --expect-workers 2

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --worker
      --master-host master
    depends_on:
      - master
