#!/bin/bash

sudo apt update && sudo apt upgrade -y

# set ip a
sudo tee /etc/netplan/01-netcfg.yaml << EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.100.110/24 
      routes:
        - to: default
          via: 192.168.100.254
      nameservers:
        addresses: [192.168.100.254, 8.8.8.8]
EOF

sudo chmod 600 01-netcfg.yaml
sudo netplan apply

# #############################
sudo apt install -y git
rm -rf ~/project-shared-bike
mkdir -pv ~/project-shared-bike
git clone https://github.com/simonangel-fong/Portfolio-Project-Toronto-Shared-Bike-Repo.git ~/project-shared-bike

cd ~/project-shared-bike
git checkout feature/dw
bash ~/project-shared-bike/data-warehouse/script/init.sh