networks:
  jenkins_network:
    driver: bridge
volumes:
  jenkins_data: {}

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    ports:
      - "8080:8080"
      - "50000:50000"
