networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_data: {}

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    ports:
      - "8080:8080"
      - "50000:50000"
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y docker.io git ca-certificates openssh-client &&
        rm -rf /var/lib/apt/lists/* &&
        /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
