pipeline {
  agent any

  environment {
    POSTGRES_USER = credentials('postgres_user')
    POSTGRES_PASSWORD = credentials('postgres_password')
    POSTGRES_DB = credentials('postgres_db')
  }

  stages {

    // stage('Cleanup Workspace & Checkout') {
    //   steps {
    //     echo "#################### Cleans the workspace ####################"
    //     cleanWs()
        
    //     echo "#################### Checkout ####################"
    //     checkout scm // Explicitly checks out the SCM after cleaning.

    //     sh """
    //       ls
    //       pwd
    //       echo "${POSTGRES_USER}"
    //     """
    //   }
    // }

    stage('Start PostgreSQL') {
      steps {
        dir('data-warehouse/postgresql'){
          echo "#################### Spin up PGDB ####################"
          sh '''
            docker compose down -v
            docker compose up -d
          '''

          echo "#################### Confirm PGDB ####################"
          sh '''
            docker ps
            docker logs --tail=100 postgresql || true
          '''
        }
      }
    }
  }
}
 