name: toronto-shared-bike

include:
  - ../nginx/docker-compose.yaml

networks:
  ingress_net:
    driver: bridge

services:
  cloudflare:
    container_name: cloudflare
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ingress_net
    command: tunnel run
    depends_on:
      - nginx

