jenkins:
  systemMessage: "Project Toronto Shared Bike - Jenkins Dashboard"

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}

credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          id: "POSTGRES_PASSWORD"
          scope: GLOBAL
          secret: ${POSTGRES_PASSWORD}
      - string:
          id: "POSTGRES_USER"
          scope: GLOBAL
          secret: ${POSTGRES_USER}

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

jobs:
  - script: >
      pipelineJob('docker-agent-test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/simonangel-fong/Portfolio-Project-Toronto-Shared-Bike-Repo.git')
                }
                branch('feature/dw')
              }
            }
            scriptPath('data-warehouse/jenkins/Jenkinsfile')
          }
        }
      }