jenkins:
  systemMessage: "Project Toronto Shared Bike - Jenkins Dashboard"

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}

# credentials:
#   system:
#     domainCredentials:
#     - credentials:
#       - secretText:
#           scope: GLOBAL
#           id: "POSTGRES_USER"
#           secret: "${POSTGRES_USER}"
#       - secretText:
#           scope: GLOBAL
#           id: "POSTGRES_PASSWORD"
#           secret: "${POSTGRES_PASSWORD}"

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

jobs:
  - script: >
      pipelineJob('docker-agent-test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/simonangel-fong/Portfolio-Project-Toronto-Shared-Bike-Repo.git')
                }
                branch('feature/dw')
              }
            }
            scriptPath('data-warehouse/jenkins/Jenkinsfile')
          }
        }
      }