jenkins:
  systemMessage: "Project Toronto Shared Bike - Jenkins Dashboard"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

credentials:
  system:
    domainCredentials:
    - credentials:
      - aws:
          accessKey: ""
          id: "aws_cred"
          scope: GLOBAL
          secretKey: ""
      - usernamePassword:
          id: "gmail_cred"
          password: ""
          scope: GLOBAL
          username: "tech.arguswatcher@gmail.com"
          usernameSecret: true
      - string:
          id: "postgres_user"
          scope: GLOBAL
          secret: ""
      - string:
          id: "postgres_db"
          scope: GLOBAL
          secret: ""
      - string:
          id: "postgres_password"
          scope: GLOBAL
          secret: ""

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  location:
    adminAddress: "tech.arguswatcher@gmail.com"
    url: "http://on-prem:8080/"
  email-ext:
    mailAccount:
      credentialsId: "gmail_cred"
      smtpHost: "smtp.gmail.com"
      smtpPort: "465"
      useSsl: true
  mailer:
    authentication:
      password: ""
      username: "tech.arguswatcher@gmail.com"
    charset: "UTF-8"
    smtpHost: "smtp.gmail.com"
    smtpPort: "465"
    useSsl: true
    useTls: false

# jobs:
#   - script: >
#       pipelineJob('my_repo_pipeline') {
#         definition {
#           cpsScm {
#             scm {
#               git {
#                 remote {
#                   url('https://github.com/simonangel-fong/Tutorial-Jenkins.git')
#                 }
#                 branch('*/master')
#               }
#             }
#             scriptPath('module-docker-compose-JCasC/pipeline/Jenkinsfile')
#           }
#         }
#       }