jenkins:
  systemMessage: "Project Toronto Shared Bike - Jenkins Dashboard"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

credentials:
  system:
    domainCredentials:
    - credentials:
      - aws:
          accessKey: ""
          id: "aws_cred"
          scope: GLOBAL
          secretKey: ""
      - usernamePassword:
          id: "gmail_cred"
          password: ""
          scope: GLOBAL
          username: "tech.arguswatcher@gmail.com"
          usernameSecret: true
      - string:
          id: "postgres_user"
          scope: GLOBAL
          secret: ""
      - string:
          id: "postgres_db"
          scope: GLOBAL
          secret: ""
      - string:
          id: "postgres_password"
          scope: GLOBAL
          secret: ""

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

unclassified:
  email-ext:
    mailAccount:
      credentialsId: "gmail_cred"
      smtpHost: "smtp.gmail.com"
      smtpPort: "465"
      useSsl: true
  # location:
  #   adminAddress: "address not configured yet <nobody@nowhere>"
  #   url: "http://on-prem:8080/"
#   mailer:
#     authentication:
#       password: ""
#       username: "tech.arguswatcher@gmail.com"
#     charset: "UTF-8"
#     smtpHost: "smtp.gmail.com"
#     smtpPort: "465"
#     useSsl: true
#     useTls: false


# jobs:
#   - script: >
#       pipelineJob('docker-agent-test') {
#         definition {
#           cpsScm {
#             scm {
#               git {
#                 remote {
#                   url('https://github.com/simonangel-fong/Portfolio-Project-Toronto-Shared-Bike-Repo.git')
#                 }
#                 branch('feature/dw')
#               }
#             }
#             scriptPath('data-warehouse/jenkins/Jenkinsfile')
#           }
#         }
#       }