pipeline {
  agent any
  stages {
    stage('Docker Version') {
      steps {
        sh 'pwd'
        sh 'ls'
        sh 'docker --version'
        sh 'docker compose -f data-warehouse/postgresql/docker-compose.yaml up -d'
      }
    }
  }
}
