name: feature-push-ci

on:
  push:
    branches:
      - "feature/**"
    # paths:
    #   - "src/**"

# control the level of access
permissions:
  contents: read

# Cancel older runs per-branch to avoid races
concurrency:
  group: dev-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lambda_unit_test:
    name: Lambda Unit Test
    runs-on: ubuntu-latest
    environment: Dev
    defaults:
      run:
        working-directory: ${{ vars.LAMBDA_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: place holder - unit test
        run: |
          pwd
          ls
          echo "Running Lambda unit tests..."

  terraform_validate:
    name: Terraform Validate / Lint / Scan
    needs: lambda_unit_test
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
    defaults:
      run:
        working-directory: ${{ vars.TF_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v3
    #     with:
    #       terraform_version: ${{ vars.TF_VERSION }}

    #   - name: Configure plugin cache dir
    #     run: |
    #       mkdir -pv /home/runner/.terraform.d/plugin-cache
    #       echo 'plugin_cache_dir = "/home/runner/.terraform.d/plugin-cache"' > /home/runner/.terraformrc
    #       echo  ${{ vars.TF_VAR_APP }}