name: Feature API Destroy(Manual) - Staging Environment

on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

concurrency:
  group: staging-destroy-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true # Cancel older runs

jobs:
  destroy_staging:
    name: Destroy Staging Env
    if: github.ref_name == 'feature-api-staging'
    runs-on: ubuntu-latest
    environment: Staging
    timeout-minutes: 60
    env:
      DIR_WEB_APP_AWS: web-app/aws
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
      TF_VERSION: 1.9.8
      TF_VAR_project: ${{ vars.PROJECT }}
      TF_VAR_app: ${{ vars.APP_WEB }}
      TF_VAR_env: ${{ vars.ENV }}
      TF_VAR_dns_domain: ${{ vars.DNS_DOMAIN }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_cloudflare_api_token: ${{secrets.CF_API_TOKEN}}
      TF_VAR_cloudflare_zone_id: ${{secrets.CF_ZONE}}
    defaults:
      run:
        working-directory: ${{ env.DIR_WEB_APP_AWS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      - name: Configure Terraform plugin cache
        run: |
          mkdir -pv ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir = "~/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}

      - name: Terraform init - S3 backend
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="key=${{ vars.AWS_BACKEND_BUCKET_KEY }}/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        run: |
          terraform fmt -check -recursive -no-color
          terraform validate -no-color

      - name: Terraform Plan - Destroy
        id: plan
        run: terraform plan -out=tfplan-destroy -input=false -no-color -destroy

      - name: Terraform Apply - Staging Destroy
        run: terraform apply -auto-approve -no-color tfplan-destroy
