name: Terraform CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "src/aws/**"

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    # The job steps
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: plan
        run: |
          echo "plan"

  # The `apply` job will run after manual approval and apply the plan.
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: plan

    # The `environment` block is crucial for manual approval.
    # The `url` field can link to a custom deployment dashboard.
    environment:
      name: Prod
      url: https://docs.github.com/en/actions/deployment/protecting-deployments

    # Configure permissions to allow for applying the plan
    permissions:
      contents: read
      id-token: write

    # The job steps
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: apply
        run: |
          echo "apply"
